---
- hosts: all
  tasks:
    - name: Content Update
      copy:
        dest: /tmp/mycmd
        content: "echo dis qmgr all"
    - name: start qmgr "{{qmgr}}"
      command: strmqm "{{qmgr}}"
    - name: dis qmgr all
      command: runmqsc "{{qmgr}}" </tmp/mycmd >/tmp/myoutput
