---
- hosts: all
  tasks:
    - name: Content Update
      copy:
        dest: /tmp/mycmd
        content: "dis qmgr all"
    #
    - name: Display qmgr name
      shell: echo Queue Manager is {{qmgr}} > /tmp/myqmgr
    #
    - name: Start qmgr  {{qmgr}} 
      command:  /opt/mqm/bin/strmqm {{qmgr}}
    #
    - name: Display qmgr all
      command: /opt/mqm/bin/runmqsc {{qmgr}} < /tmp/mycmd > /tmp/myoutput
