---
- hosts: all
  tasks:
    - name: Content Update
      copy:
        dest: /tmp/mycmd
        content: "echo dis qmgr all"
    - name: Display qmgr name
      command: echo Queue Manager " {{qmgr}} " 
    - name: start qmgr " {{qmgr}} "
      command: strmqm " {{qmgr}} "
    - name: dis qmgr all
      command: runmqsc " {{qmgr}} " </tmp/mycmd >/tmp/myoutput
