---
- hosts: all
  tasks:
    - name: Content Update
      copy:
        dest: /tmp/mycmd
        content: "dis qmgr all"
    #
    - name: Display qmgr name
      shell: echo Queue Manager is {{qmgr}} > /tmp/myqmgr
    #
    - name: Start qmgr  {{qmgr}} 
      command:  /opt/mqm/bin/strmqm {{qmgr}}
      register: command_result
      failed_when: "'FAILED' in command_result.stderr"
    #
    -  name: Sleep for 60 seconds and timeout
       tags: sleep60
       wait_for:
         delay: 60
         timeout: 0
    #
    - name: Display qmgr all
      command: /opt/mqm/bin/runmqsc {{qmgr}} -f /tmp/mycmd 
