---
- hosts: all
  tasks:
    - name: Content Update
      copy:
        dest: /tmp/test123
        content: "Hello, Tester!\n"       
    #
    - name: Install jq
      apt:
        name: jq
        state: present
        update_cache: yes
      register: jq_cmd
    - name: Install jq error
      shell: "echo cannot install jq >>/tmp/test123"
      when: jq_cmd.rc > 0
    #
    - name: Install zip
      apt:
        name: zip
        state: present
        update_cache: yes
      register: jq_cmd
    - name: Install zip error
      shell: "echo cannot install zip >>/tmp/test123"
      when: zip_cmd.rc > 0
    #
    - name: Install openssl
      apt:
        name: openssl
        state: present
        update_cache: yes
      register: openssl_cmd
    - name: Install openssl error
      shell: "echo cannot install openssl >>/tmp/test123"
      when: openssl_cmd.rc > 0
    #
    - name: Add IP address and timestamp
      shell: "ifconfig|grep 'inet '|awk '{print $2}'|egrep -v '^127.0|^10.' >>/tmp/test123;date >>/tmp/test123"
    - name: Show the file content
      shell: "cat /tmp/test123"
      register: out
    - debug: var=out.stdout_lines
