---
- hosts: all
  tasks:
    - name: Content Update
      copy:
        dest: /tmp/resolv.conf
        content: "nameserver 192.168.0.2\n"
    #
    - name: Install jq
      shell: sudo apt-get install -y jq
    #
    - name: Install zip
      shell: sudo apt-get install -y zip
    #
