---
- hosts: all
  tasks:
    - name: Content Update
      copy:
        dest: /tmp/test123
        content: "Hello, Tester!\n"       
    #
    - name: Install software package
      apt:
        update_cache: yes
        name:
          - jq
          - zip
          - nginx
          - openssl
        state: present
    - name: Gather Package facts
      package_facts:
        manager: auto
    - name: Validate the installation
      debug: 
        msg: "{{item}} is not installed"
      when:  ' item|string not in ansible_facts.packages'
      with_items:
        - jq
        - zip
        - nginx
        - openssl
    #
    - name: Add IP address and timestamp
      shell: "ifconfig|grep 'inet '|awk '{print $2}'|egrep -v '^127.0|^10.' >>/tmp/test123;date >>/tmp/test123"
    - name: Show the file content
      shell: "cat /tmp/test123"
      register: out
    - debug: var=out.stdout_lines
